services:
  proxy_server:
    restart: always
    image: proxy-server
    ports: 
      - "8080:8080"
    volumes:
      - ./db:/app/db
  
  proxy_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: on-failure
    image:  proxy-api
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    # command: ["python3", "api.py"]
